

fn f() {
    let v = java::lang::RuntimeException { _: "test" }
    throw v
}